Готовое ДЗ 1 (переделано)
V01taire/TINKOFF pull request #1
Opened 2023-10-17 17:48 UTC by V01taire

ДЗ 1 готово и исправлено)

2023-10-17 20:51 UTC, V01taire commented
В задании номер 3 была ошибка в тесте, все понял

2023-10-21 09:44 UTC, Stasik371 commented on pom.xml
> +            <version>4.13.1</version>
Давай 5 подключим лучше, 4-й уже прошлый век

2023-10-21 09:59 UTC, Stasik371 requested changes

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task0.java
> +//    public static void main(String[] args) {
Давай без комментов в коде

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task1.java
> +        int minutes = Integer.parseInt(timeParts[MINUTES_POSITION]);
Давай лучше без таких бесполезных констант) Поставь `@SupressWarning`

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        // Если число отрицательное, сделаем его положительным для удобства подсчета цифр
Хороший код тот, который не нуждается в комментариях) Удали тут и везде

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task2.java
> +        return (int) (Math.log10(numberToCountDigits) + 1);
лайк!

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task3.java
> +        int maxArray1 = Arrays.stream(array1).max().getAsInt();
Кажется, что у тебя 4 одинаковые строчки) Давай private метод сделаем)

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task4.java
> +    public String fixString(String brokenString) {
Не забывай пропускать строку)

2023-10-21 09:59 UTC, Stasik371 commented on src/main/java/edu/hw1/Task5.java
> +    private static String sumAdjacentDigits(String str) {
Первый раз в жизни такое слово вижу) У тебя С2?))

Исправлять не нужно)

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    })
Круто) Давай докинем еще тестиков на `1:59`, должно выдать -1, потому что формат `MM:ss` Еще можно `abc:def`

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        Task1 videoLength = new Task1();
Давай размечать блоки с помощью //given //when //then

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +    public void countDigitsTest() {
Один тестКейс-один тестовый метод)

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +        assertEquals(4, task.countDigits(4666));
Пользуйся лучше `assertThat`

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task2Test.java
> +        assertEquals(4, task.countDigits(4666));
Это даже в требованиях есть)
<img width="707" alt="image" src="https://github.com/V01taire/TINKOFF/assets/90406808/c9b8a334-7e69-4f8b-9737-2a6c823930ca">

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task3Test.java
> +                Arguments.of(new int[] {}, new int[] {}, false)
Давай еше на null проверим

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        assertEquals(expected, Task5.isPalindromeDescendant(input));
ААА тесты хочеца)

И еще отрицательные числа докинуть

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +            "3524, 3",
Давай добавим тест на 1111, 999, 1000 и 10000. И на отрциательное еще)

2023-10-21 09:59 UTC, Stasik371 commented on src/test/java/edu/hw1/Task7Test.java
> +    @CsvSource({"16, 1, 1", "17, 2, 6"})
Докинь тестов на отрицательный сдвиг, тут сам можешь придумать логику реализации.

2023-10-29 17:21 UTC, merged